apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: anubhav1404/user-backend:v2
        ports:
        - containerPort: 8080
        env:
        - name: POSTGRES_DB
          value: "postgres"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
        - name: POSTGRES_HOST
          value: "postgres-service"
        resources:
          requests:
            cpu: "50m"       # slightly above observed usage
            memory: "200Mi"
          limits:
            cpu: "250m"
            memory: "512Mi"

