version: '3.8'

services:
  # Backend Service
  backend:
    build:
      context: ./user
    container_name: user_backend
    ports:
      - "8080:8080"   # Host port mapping stays the same
    depends_on:
      - ai_service
    networks:
      - app_network

  # AI Service
  ai_service:
    build:
      context: ./translate
    container_name: user_ai_service
    ports:
      - "8081:8081"   # Host port mapping stays the same
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    networks:
      - app_network

  # Frontend Service
  frontend:
    build:
      context: ./user-microservice-frontend
    container_name: user_frontend
    ports:
      - "3000:80"   # Host port mapping stays the same
    depends_on:
      - backend
    networks:
      - app_network

# User-defined network for DNS-like behavior
networks:
  app_network:
    driver: bridge
