apiVersion: v1
kind: Service
metadata:
  name: ai-service
spec:
  selector:
    app: ai-service
  ports:
    - protocol: TCP
      port: 80          # external service port
      targetPort: 8081  # container port inside pod
  type: ClusterIP  # or ClusterIP if internal only
