apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: anubhav1404/user-frotend:v3
        ports:
        - containerPort: 80
        command: ["nginx", "-g", "daemon off;"]  # run NGINX with default config only

