apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: frontend-netpol
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: frontend
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Allow ingress only from NGINX ingress
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: ingress-nginx
    ports:
    - protocol: TCP
      port: 80
  egress:
  # Frontend → Backend (container port 8080)
  - to:
      - podSelector:
          matchLabels:
            app: backend
    ports:
    - protocol: TCP
      port: 8080
  # Frontend → AI service (container port 8081)
  - to:
      - podSelector:
          matchLabels:
            app: ai-service
    ports:
    - protocol: TCP
      port: 8081
  # Frontend → DNS (TCP & UDP 53)
  - to:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: kube-system
        podSelector:
          matchLabels:
            k8s-app: kube-dns
    ports:
      - protocol: UDP
        port: 53
      - protocol: TCP
        port: 53

